### ISSUE TITLE
4k problem with Web Emu

### ISSUE THREAD

**Issue by MacGyver4B** [visrealm/hbc-56#4]
Hello Troy,
I found a problem with 4k resolution and the web based Emu, is not properly working see picture.
![image](https://user-images.githubusercontent.com/102614113/160716077-b34f82b5-af2a-49ed-ac4f-0b5bfa826998.png)

If I reduce screen resolution to 1080p AND set zoom to 80%, the debug info is there.

Workaround I tried the same trick if I zoom to 67% debug Data is there but everything is very small.

![image](https://user-images.githubusercontent.com/102614113/160799157-9bf96512-2566-4d57-851a-c54b2720ebaa.png)

Best regards
Stefan

**Comment by MacGyver4B** [comment]
None Web Version works perfectly fine.

**Comment by visrealm** [comment]
Thanks for the report. I finally have a system I can reproduce this issue on. I'll look into it.

**Comment by visrealm** [comment]
Fixed and tested with my high dpi display.
