### ISSUE TITLE
make: *** No rule to make target 'obj/src/window.o', needed by 'hbc56emu'.  Stop.

### ISSUE THREAD

**Issue by bearney74** [visrealm/hbc-56#9]
makefile does not work under linux.

I get the following error when I try to run emulator/linux/makefile:
`
make: *** No rule to make target 'obj/src/window.o', needed by 'hbc56emu'.  Stop.
`
I cannot find a window.c file.

**Comment by bearney74** [comment]
I created a pull request for this.

**Comment by visrealm** [comment]
PR10

**Comment by visrealm** [comment]
PR#10
